DROP TABLE projects CASCADE;
DROP TABLE designs CASCADE;
DROP TABLE builds CASCADE;
DROP TABLE prints CASCADE;
DROP TABLE parts CASCADE;
DROP TABLE post_processes CASCADE;

DROP TABLE orders CASCADE;
DROP TABLE prepares CASCADE;
DROP TABLE refinements CASCADE;